config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "accounts#index"

  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'accounts/:id/items.csv', to: 'accounts#items_to_csv', as: 'items_to_csv'

  resources :accounts , shallow: true do
      get :multi_exhibit, on: :member
      get :schedule, on: :member
      post :get_comment, on: :member, to: "comments#get_multi_comment"
      get :item_exhibited, to: "items#item_exhibited"
      get :item_not_exhibit, to: "items#item_not_exhibit"
      # get :re_exhibit, to: "items#re_exhibit"
      get :re_exhibit, to: "items#re_exhibit"
      post :re_exhibit, to: "items#exec_re_exhibit",as: 'exec_re_exhibit'

         resources :items, shallow: true do
             get :exhibit, on: :member
             post :get_comment, on: :member, to: "comments#get_comment"
             delete :destroy_multi, on: :collection, to: 'items#destroy_multi'
             resources :comments, shallow: true
             end
         end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :account
  has_many :comments, dependent: :destroy
 #  validates :csv, presence: true
 #  validates :item_name,   presence: true, length: { maximum: 30}
 #  validates :description,   presence: true, length: { maximum: 1000}
 #  validates :category1,     presence: true, numericality: true
 #  validates :category2,     presence: true, numericality: true
 #
 #  validates :state,
 #  presence: true, numericality: { only_integer: true,
 #  greater_than: -1, less_than: 6
 #  }
 #
 #  validates :ship_fee,
 #  presence: true, numericality: { only_integer: true,
 #  greater_than: -1, less_than: 3
 #  }
 #
 #  validates :ship_method, presence: true, numericality: true
 #
 #  validates :ship_from,
 #  presence: true, numericality: { only_integer: true,
 #  greater_than: 0, less_than: 48
 #  }
 #
 #  validates :ship_day,
 #  presence: true, numericality: { only_integer: true,
 #  greater_than: -1, less_than: 3
 #  }
 #
 # validates :purchase_application,
 # presence: true, numericality: { only_integer: true,
 # greater_than: -1, less_than: 2
 # }
 #
 #  validates :price,             presence: true,  numericality: true
 #
 #  validate :tags_character_size
 #  validate :ship_method_check
 #
 #  def tags_character_size
 #      if !tags.nil? && tags.gsub("：","").gsub(":","").size > 20 #タグが存在し、かつ２０文字以上ならエラー
 #        errors.add(:tags, "タグは20文字以内です")
 #     end
 #  end
 #
 #  def ship_method_check
 #     unless ship_method == 3 or ship_method == 14 or ship_method == 8 or ship_method == 2 or ship_method == 4 or ship_method == 0
 #        errors.add(:ship_method, "そのような配送方法はありません")
 #     end
 #  end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    require "csv"
    require "zip"
    require 'fileutils'

    before_action :authenticate_user!
    before_action :current_user_check, only: [:show, :edit, :update, :destroy, :exhibit]

    def index
        @account = Account.find(params[:account_id])
        @items = @account.items.all
    end

    def item_exhibited
        @account = Account.find(params[:account_id])
        @items_exhibited = @account.items.where.not(url: nil)
        # @items = @account.items.all
    end

    def item_not_exhibit
        @account = Account.find(params[:account_id])
        @items_not_exhibited = @account.items.where(url: nil)
    end

    def create
      @account = Account.find(params[:account_id])
      uploaded_file = item_params[:csv]
      hash_name = uploaded_file.hash.to_s
      if Time.now - @account.access_time > 120
              #ファイルの保存先
              output_path = Rails.root.join('public/zip_store',  hash_name + uploaded_file.original_filename)
              #ファイル保存
              File.open(output_path, 'wb') do |f|
                f.write  uploaded_file.read
              end
              Zip::File.open(output_path) do |zip|
                        zip.each do |entry|
                            destination = Rails.root.join('public/zip_store',  hash_name + "/")
                            dir = File.join(destination, File.dirname(entry.name))
                            FileUtils.mkpath(dir)
                                        zip.extract(entry, destination + entry.name) { true }
                                                    if entry.name == "exhibit/item.csv"
                                                                    begin
                                                                         CSV.table(destination + "exhibit/item.csv",encoding: 'Shift_JIS:UTF-8').each do |row| #windowsの時
                                                                            csv_insert(row,hash_name)
                                                                         end
                                                                    rescue
                                                                         CSV.table(destination + "exhibit/item.csv").each do |row| #macの時
                                                                            csv_insert(row,hash_name)
                                                                         end
                                                                    end
                                                    end
                        end
              end
              # multi_exhibit #登録した後にすぐに出品
     end
      logger.debug "#{Time.now - @account.access_time}"
      redirect_to account_path(@account)
    end

    def multi_exhibit
        @account = Account.find(params[:account_id])
        if Time.now - @account.access_time > 120 #現在の時刻と前回の時刻との差が60(新しいリクエストが送られるまで)より大きければtrue
            logger.debug "#{Time.now - @account.access_time}"
            logger.debug '#######pass###########'
            logger.info  'LOGGER TEST >>> info'
            @account.access_time =  Time.now
            @account.save

            @ota = Otamart.new
            driver = @ota.login(@account.account_email,@account.account_password)
            n = 1
            items = @account.random_exhibit ? @account.items.where(url:nil).order("RANDOM()") : @account.items.where(url:nil)#ランダム出品するかどうか
                for item in items.all do #driver.closeしなければならないため、スコープを作らないfor分を使用。
                         file_abs_path = Rails.root.join('public/zip_store', item.csv.to_s + "/exhibit/")
                         @account.access_time =  Time.now#ここで出品中は常に時間を更新することで、2回目に送られてくるリクエストが、Time.now - @account.access_time > 60にtrueにならないようにする
                         @account.save
                         logger.debug '#######after_pass############'
                         logger.debug "#{Time.now - @account.access_time}"
                         logger.debug "#{n}"
                         logger.info  'LOGGER TEST >>> info'
                         url, driver = @ota.multi_exhibit(driver,file_abs_path,item.image1,item.image2,item.image3,item.image4,item.item_name,item.description,item.category1,item.category2,item.category3,
                             item.tags,item.state,item.ship_fee,item.ship_method,item.ship_from,item.ship_day,item.purchase_application,item.discount,item.price)
                         item.url = url
                         item.save

                         unless  @account.min_interval.blank? or @account.max_interval.blank?
                               logger.debug "#{Random.new().rand(@account.min_interval.to_i...@account.max_interval.to_i)}"
                               sleep(Random.new().rand(@account.min_interval.to_i..@account.max_interval.to_i))
                           else
                               sleep(Random.new().rand(5.0..15.0))
                          end

                        n += 1
                        @account.access_time =  Time.now#ここで出品中は常に時間を更新することで、2回目に送られてくるリクエストが、Time.now - @account.access_time > 60にtrueにならないようにする
                        @account.save
                end
            driver.close
            driver.quit
        else
            logger.debug "#{Time.now - @account.access_time}"
            logger.debug '#######no############'
            logger.info  'LOGGER TEST >>> info'
        end
    end


    def csv_insert(row,hash_name)
            @item = @account.items.new(item_params)
            @item.csv = hash_name
            @item.item_name = row[0]
            @item.description = row[1]
            @item.image1 = row[2]
            @item.image2 = row[3]
            @item.image3 = row[4]
            @item.image4 = row[5]
            @item.price = row[6]
            @item.category1 = row[-11]
            @item.category2 = row[-10]
            @item.category3 = row[-9]
            @item.tags = row[-8]
            @item.state = row[-7]
            @item.ship_fee = row[-6]
            @item.ship_method = row[-5]
            @item.ship_from = row[-4]
            @item.ship_day = row[-3]
            @item.purchase_application = row[-2]
            @item.discount = row[-1]
            @item.count_comments = 0
            @item.new_comment = false
            #ここで保存失敗した時の挙動を設定する
            @item.save
    end


    def show
        @item = Item.find(params[:id])
        @account = @item.account
        @comments = @item.comments.all
    end

    def edit
        @item = Item.find(params[:id])
        @account = @item.account
    end

    def update
        @item = Item.find(params[:id])
        @account = @item.account
            if Time.now - @account.access_time > 10 #現在の時刻と前回の時刻との差が60(新しいリクエストが送られるまで)より大きければtrue
                    logger.debug "#{Time.now - @account.access_time}"
                    logger.debug '#######pass###########'
                    @account.access_time =  Time.now
                    @account.save

                    if !item_update_params[:image1].blank?
                        uploaded_file1 = item_update_params[:image1]
                        file_abs_path1 = Rails.root.join('public/zip_store', @item.csv.to_s + "/exhibit/" + uploaded_file1.original_filename)
                    	File.open(file_abs_path1, 'w+b') do |fp|
                    	    fp.write  uploaded_file1.read
                    	end
                        image1 = uploaded_file1.original_filename
                    else
                        image1 = ""
                    end

                    if !item_update_params[:image2].blank?
                        uploaded_file2 = item_update_params[:image2]
                        file_abs_path2 = Rails.root.join('public/zip_store', @item.csv.to_s + "/exhibit/" + uploaded_file2.original_filename)
                        File.open(file_abs_path2, 'w+b') do |fp|
                          fp.write  uploaded_file2.read
                        end
                        image2 = uploaded_file2.original_filename
                    else
                        image2 = ""
                    end

                    if !item_update_params[:image3].blank?
                        uploaded_file3 = item_update_params[:image3]
                        file_abs_path3 = Rails.root.join('public/zip_store', @item.csv.to_s + "/exhibit/" + uploaded_file3.original_filename)
                        File.open(file_abs_path3, 'w+b') do |fp|
                          fp.write  uploaded_file3.read
                        end
                        image3 = uploaded_file3.original_filename
                    else
                        image3 = ""
                    end

                    if !item_update_params[:image4].blank?
                        uploaded_file4 = item_update_params[:image4]
                        file_abs_path4 = Rails.root.join('public/zip_store', @item.csv.to_s + "/exhibit/" + uploaded_file4.original_filename)
                        File.open(file_abs_path4, 'w+b') do |fp|
                          fp.write  uploaded_file4.read
                        end
                        image4 = uploaded_file4.original_filename
                    else
                        image4 = ""
                    end

                    @ota = Otamart_edit.new
                    driver = @ota.login(@account.account_email,@account.account_password,@item.url.gsub("comments","edit"))
                    file_abs_path = Rails.root.join('public/zip_store', @item.csv.to_s + "/exhibit/")

                    result = @ota.item_edit(driver,file_abs_path, image1, image2,image3,image4,
                                    params[:item][:item_name], params[:item][:description], params[:item][:category1], params[:item][:category2],
                                    params[:item][:category3], params[:item][:tags], params[:item][:state], params[:item][:ship_fee],

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@account.items.new, url: polymorphic_path([@account, @account.items.new], html: {id:'product_upload_form', class:'orm-horizontal col-xs-11', style:''})) do |f| %>
<div id="product_input_wrapper">

    <div class="form-group" style="text-align:center;">
        <label class="col-xs-3 control-label">商品ファイル(zip形式) </label>
        <div class="col-xs-8 control-label">
             <%= f.file_field :csv, :class => 'form-control input-sm',:id => 'product_file' %>
        </div>
    </div>

    <div class="form-group" style="text-align:center;">
        <!-- <button type="button" onclick="javascript:uploadProduct()" id="publish_upload" name="publish_upload" class="btn btn-success" style="float:none; margin: 0 auto">アップロード</button> -->
         <%= f.submit 'アップロード', :class => 'btn btn-success',  :id => "publish_upload"  %>
    </div>
</div>
<% end %>

app/views/items/index.html.erb
<section class="content-header">
        <h1>
            登録中の商品
        </h1>
        <ol class="breadcrumb">
            <li><i class="fa fa-home"></i>ホーム</li>
            <li class="active"><i class="fa fa-comment"></i> <b>登録中の商品</b></li>
        </ol>
</section>

<h3 class="box-title">登録中の商品の商品一覧</h3>
                    <%= form_tag destroy_multi_account_items_path, method: :delete  ,class: "form-horizontal",  id: "product_main" do %>
                        <div class="box-body table-responsive  with-border" id="main_tbl_wrap" name="main_tbl_wrap">
                            <div id="main_tbl_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">

                            <div class="row">
                                <div class="col-sm-12">
                                    <table id="main_tbl" class="table table-hover dataTable no-footer" role="grid" aria-describedby="main_tbl_info" border="1">
                                        <thead>
                                            <tr role="row">
                                                <th align="center" style="padding-right: 0px; width: 20px;" class="sorting_disabled" rowspan="1" colspan="1" aria-label="">
                                                    <%= check_box_tag "items_destroy_all[#{ @items.ids }]", @items.ids %>
                                                </th>
                                                <th style="text-align: center; padding-right: 0px; min-width: 100px !important; width: 100px;" class="sorting" tabindex="0" aria-controls="main_tbl" rowspan="1" colspan="1" aria-label="画像: この列の昇順に">画像</th>
                                                <th style="text-align: center; padding-right: 0px; min-width: 50px !important; width: 268px;" class="sorting" tabindex="0" aria-controls="main_tbl" rowspan="1" colspan="1" aria-label="商品名: この列の昇順に">商品名</th>
                                                <!-- <th style="text-align: center; padding-right: 0px; min-width: 250px !important; width: 250px;" class="sorting" tabindex="0" aria-controls="main_tbl" rowspan="1" colspan="1" aria-label="出品日: この列の昇順に">出品日</th> -->
                                                <th style="text-align: center; padding-right: 0px; min-width: 80px !important; width: 80px;" class="sorting" tabindex="0" aria-controls="main_tbl" rowspan="1" colspan="1" aria-label="価格: この列の昇順に">価格</th>
                                                <!-- <th style="text-align: center; padding-right: 0px; min-width: 100px !important; width: 100px;" class="sorting_desc" tabindex="0" aria-controls="main_tbl" rowspan="1" colspan="1" aria-label="いいね数: この列の昇順に" aria-sort="descending">いいね数</th> -->
                                                <th style="text-align: center; padding-right: 0px; min-width: 100px !important; width: 100px;" class="sorting" tabindex="0" aria-controls="main_tbl" rowspan="1" colspan="1" aria-label="コメント: この列の昇順に">コメント</th>
                                                <!-- <th style="text-align: center; padding-right: 0px; width: 70px;" class="sorting" tabindex="0" aria-controls="main_tbl" rowspan="1" colspan="1" aria-label="備考: この列の昇順に">備考</th> -->
                                                <!-- <th style="text-align: center; padding-right: 0px; width: 58px;" class="sorting" tabindex="0" aria-controls="main_tbl" rowspan="1" colspan="1" aria-label="操作: この列の昇順に">操作</th> -->
                                            </tr>
                                        </thead>
                                        <tbody>

                                            <% @items.each do |item| %>
                                                <tr role="row" class="odd">
                                                    <td align="center" style="vertical-align: top;">
                                                        <%= check_box_tag "items_destroy[#{ item.id }]", item.id %>
                                                    </td>

                                                        <td style="text-align: center;vertical-align:top;">
                                                            <a href="/furiru-products/product_detail_edit?furiru_id=184794469">
                                                                <%= image_tag("/zip_store/" + item.csv.to_s + "/exhibit/"  + item.image1, :id => "photo_1_preview", :style => "cursor: pointer;width:100px;") %>
                                                            </a>
                                                        </td>
                                                        <td style="vertical-align:top;font-weight: bold">
                                                            <%= link_to  item.item_name, item_path(item),  account_id:item.account_id %>
                                                        </td>
                                                        <td style="text-align: center;vertical-align:top">
                                                            <div class="input-group input-group-sm" style="text-align: center"><%= item.price %>円</div>
                                                        </td>
                                                        <td style="text-align: center;vertical-align:top">
                                                            <a id="comment_count_303" href="javascript:displayComments(303,2)">
                                                                <% if item.new_comment %>
                                                                       あり
                                                                <% else %>
                                                                       なし
                                                                <% end %>
                                                            </a>
                                                                <br>
                                                        </td>
                                                </tr>
                                            <% end %>

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                                </div>
                        </div>

                            <div class="box-footer text-right">
                                <div class="row">
                                    <div class="col-xs-6 col-md-6">
                                        <%= submit_tag "削除" , :class => "btn btn-danger btn-sm pull-left", :id => "save_product", :style=>"margin-left: 15px" %>
                                    </div>

                                    <div class="col-xs-6 col-md-6">
                                        <% if @items.size > 0 %>
                                            <%= link_to 'すべてのコメント取得', get_comment_account_path(@account), method: :post ,class: "btn btn-primary" %>
                                        <% else %>
                                            <a style="float: right;" type="button" class="btn btn-warning">コメントを取得できる商品がありません</a>
                                        <% end %>
                                    </div>


                                </div>
                            </div>
                        </div>
                    <% end %>

                </div>
            </div>
        </div>
</section>

app/views/items/re_exhibit.html.erb
<section class="content-header">
        <h1>
            出品管理
<!--            <small>出品一覧</small>-->
        </h1>
        <ol class="breadcrumb">
            <li>ホーム</li>
            <li class="active"><b>商品出品設定</b></li>
        </ol>
    </section>


    <section class="content">
        <div class="row" id="list_container" name="list_container">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">商品出品設定</h3>
                        <!-- <a type="button" class="btn btn-primary" href="/user-products/product_add_local">
                            <span class="glyphicon glyphicon-plus"></span>新規登録
                        </a> -->
                    </div>

            <%= form_tag(account_exec_re_exhibit_path, method: :post) do %>
                <%#= select_tag 'note[point]', options_for_select(["全て再出品", "コメントのある商品以外再出品"]) %>
　　　    <%= select_tag(:re_exhibit, options_for_select([ ["全て再出品（全ての既存の商品を削除して同じ商品を再出品）", "1"],
                         ["コメントのある商品以外再出品（コメントある商品は再出品せず、それ以外再出品）", "2"]] ))  %>

                        <!-- <select name="republish-all" onchange="updateRepublish(this);" onfocus="this.selectedIndex=-1;">
                            <option value="3">コメントのある商品停止</option>
                            <option value="2">重複出品</option>
                            <option value="1">再出品する</option>
                            <option value="0">再出品しない</option>
                            <option value="-1">コメントのある商品重複</option>
                        </select> -->
                    <div class="box-footer text-right">
                        <div class="row">
                            <div class="col-xs-12">
                                <!-- <button type="button" onclick="RemoveCheckedProduct()" class="btn btn-danger btn-sm pull-left" style="margin-left: 15px" data-style="zoom-in">
                                    再出品実行
                                </button> -->
                                <%= submit_tag "再出品実行" , {:class => 'btn btn-danger btn-sm pull-left' ,  :style => "margin-left: 15px"} %>
                            </div>
                        </div>
                    </div>
            <% end %>



                    <div id="loading_overlay" class="overlay" style="display: none;">
                        <i class="fa fa-refresh fa-spin"></i>
                    </div>

                </div>
            </div>
        </div>
    </section>

app/views/items/show.html.erb
    <div class="container">
        <div class="row">
                <div class="col-lg-12 text-center">
                    <h1>
                        商品詳細
                    </h1>
                    <table class="table">
                      <thead>
                        <tr class="table-active">
                          <th scope="col">商品名</th>
                          <th scope="col">
                              <%=@item.item_name %>
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr class="table-light">
                          <th scope="row">商品説明</th>
                          <td>
                              <%=@item.description %>
                          </td>
                        </tr>
                        <tr class="table-light">
                          <th scope="row">画像</th>
                          <td>
                              <%= image_tag("/zip_store/" + @item.csv.to_s + "/exhibit/"  + @item.image1, :id => "photo_1_preview" , :size => "150x150") %>
                          </td>
                        </tr>
                        <tr class="table-light">
                          <th scope="row">販売価格</th>
                          <td>
                              <%=@item.price %>円
                          </td>
                        </tr>
                        <tr class="table-light">
                          <th scope="row">オタマートカテゴリー1</th>
                          <td>
                              <%=@item.category1 %>
                          </td>
                        </tr>
                        <tr class="table-light">
                          <th scope="row">オタマートカテゴリー2</th>
                          <td>
                              <%=@item.category1 %>
                          </td>
                        </tr>
                        <tr class="table-light">
                          <th scope="row">オタマートカテゴリー3</th>
                          <td>
                              <%=@item.category1 %>
                          </td>
                        </tr>
                        <tr class="table-light">
                          <th scope="row">商品の状態</th>
                          <td>
                              <%=@item.state %>
                          </td>
                        </tr>
                        <tr class="table-light">
                          <th scope="row">送料の表示</th>
                          <td>
                              <%=@item.ship_fee %>
                          </td>
                        </tr>
                        <tr class="table-light">
                          <th scope="row">配送方法</th>
                          <td>
                              <%=@item.ship_method %>
                          </td>
                        </tr>
                        <tr class="table-light">
                          <th scope="row">発送元の地域</th>
                          <td>
                              <%=@item.ship_from %>
                          </td>
                        </tr>
                        <tr class="table-light">
                          <th scope="row">発送日の目安</th>
                          <td>
                              <%=@item.ship_day %>
                          </td>
                        </tr>
                        <tr class="table-light">
                          <th scope="row">購入申込みの承諾</th>
                          <td>
                              <%=@item.purchase_application %>
                          </td>
                        </tr>
                        <tr class="table-light">
                          <th scope="row">値下げしませんを表示する</th>
                          <td>
                              <%=@item.discount %>
                          </td>
                        </tr>
                        <tr class="table-light">
                          <th scope="row">URL</th>
                          <td>
                              <%=@item.url %>
                          </td>
                        </tr>
                        <tr class="table-light">
                            <th scope="row">未返信コメント</th>
                            <td>
                                <% if @item.new_comment == true%>
                                    <p>あり</p>
                                <% elsif %>
                                    <p>なし</p>
                                <% end %>
                            </td>
                        </tr>
                        <tr class="table-light">
                            <th scope="row">総コメント数</th>
                            <td><%=@item.count_comments %></td>
                        </tr>
                      </tbody>
                    </table>
                </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-lg-4"></div>
            <div class="col-lg-4 text-center">
                <%= link_to '商品一覧', @account,  class: "btn btn-outline-success", id: "publish_product" %>
                <% unless @item.url.blank? %>
                      <%= link_to '商品編集', edit_item_path(@item), class: "btn btn-outline-success", id: "cancel_preview" %>
                      <div class="alert alert-dismissible alert-success">
                          <button type="button" class="close" data-dismiss="alert">&times;</button>
                          <strong>この商品は出品済みです</strong>
                     </div>
                  <% else %>
                       <%= link_to 'この商品を出品する', exhibit_item_path(@item), class: "btn btn-outline-success", id: "publish_product" %>
                <% end %>
            </div>
            <div class="col-lg-4"></div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-lg-2"></div>
            <div class="col-lg-8">
                <h2>コメント</h2>
                <% if !@item.url.blank? %>
                        <% @comments.each do |comment| %>
                        <p>名前:<%= comment.name %></p>
                        <p>内容:<%= comment.content %></p>
                        <p>---------------------------------</p>
                        <% end %>
                          <p><%= link_to 'コメント取得', get_comment_item_path(@item), method: :post %></p>
                        <%= render "comments/form" %>
                <% elsif %>
                        <div class="alert alert-dismissible alert-warning">
                          <button type="button" class="close" data-dismiss="alert">&times;</button>
                          <strong>まだ出品されていないためコメントの取得・投稿はできません</strong>
                        </div>
                <% end %>
           </div>
            <div class="col-lg-2"></div>
        </div>
   </div>