config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "accounts#index"

  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'accounts/:id/items.csv', to: 'accounts#items_to_csv', as: 'items_to_csv'

  resources :accounts , shallow: true do
      get :multi_exhibit, on: :member
      get :schedule, on: :member
      post :get_comment, on: :member, to: "comments#get_multi_comment"
      get :item_exhibited, to: "items#item_exhibited"
      get :item_not_exhibit, to: "items#item_not_exhibit"
      # get :re_exhibit, to: "items#re_exhibit"
      get :re_exhibit, to: "items#re_exhibit"
      post :re_exhibit, to: "items#exec_re_exhibit",as: 'exec_re_exhibit'

         resources :items, shallow: true do
             get :exhibit, on: :member
             post :get_comment, on: :member, to: "comments#get_comment"
             delete :destroy_multi, on: :collection, to: 'items#destroy_multi'
             resources :comments, shallow: true
             end
         end
end

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
	<head>
		<meta charset="utf-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<title>Localotamart</title>
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>
	   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	   <%=  javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

	   <!-- Bootstrap CSS -->
	   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<style>
			html, body {
				height: 100%;
			}
		</style>
	</head>

	<body class="skin-black-custom sidebar-mini wysihtml5-supported">
		<% if user_signed_in? %>
				<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
				  <a class="navbar-brand" href="#">Navbar</a>
				  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
				    <span class="navbar-toggler-icon"></span>
				  </button>
				  <div class="collapse navbar-collapse" id="navbarColor02">
				    <ul class="navbar-nav mr-auto">
				      <li class="nav-item">
							<% unless current_user.accounts.blank? %>
								 <% current_user.accounts.each do |account| %>
								 <%= link_to account.account_email,  account ,class: :"nav-link" %>
								<% end %>
							<% end %>
				      </li>
					  <% if current_user.admin_flg %>
					      <li class="nav-item">
							  <%= link_to "管理画面", "/admin" ,class: :"nav-link" %>
					      </li>
					       <li class="nav-item">
							   <%= link_to "アカウント付与", "/admin/user" ,class: :"nav-link" %>
						  </li>
					  <% end %>
				      <li class="nav-item">
				        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete ,class: :"nav-link" %>
				      </li>
				      <li class="nav-item">
				        <%= link_to 'アカウント管理', accounts_path ,class: :"nav-link" %>
				      </li>
					  <li class="nav-item">
						  <% begin %>
								  <% if !current_page?(new_account_path) %>
											  <%= link_to 'スケジュール設定', schedule_account_path(@account) ,class: :"nav-link" %>
								 <% end %>
						  <% rescue %>
						  <% end %>
					  </li>
					  <li class="nav-item">
						  <% if @account %>
							 <%= link_to '商品一括登録', @account ,class: :"nav-link" %>
						  <% end %>
					  </li>
					  <li class="nav-item">
						  <% begin %>
						     <%= link_to '商品出品設定', account_re_exhibit_path ,class: :"nav-link" %>
						  <% rescue%>
						  <% end %>
					  </li>
					  <li class="nav-item">
						  <% begin %>
								  <% unless @account.blank? %>
										  <%= link_to '登録商品', account_items_path(@account) ,class: :"nav-link" %>
								  <% end %>
						   <% rescue %>
						  <% end %>
					  </li>
					  <li class="nav-item">
							<% begin %>
									<% unless @account.blank? %>
											  <%= link_to '出品中', account_item_exhibited_path(@account) ,class: :"nav-link" %>
									 <% end %>
							<% rescue %>
							<% end %>
					  </li>
					  <li class="nav-item">
						  <% begin %>
								  <% unless @account.blank? %>
										  <%= link_to '未出品', account_item_not_exhibit_path(@account) ,class: :"nav-link"  %>
								  <% end %>
						  <% rescue %>
						  <% end %>
					  </li>
				    </ul>
				  </div>
				</nav>
				<div class="content-wrapper">
						<%= yield %>
				</div>
	    <% else %>
              <% if current_page?(new_user_registration_path) %>
				  <%= render "devise/registrations/new" %>
				<% else %>
			      <%= render "devise/sessions/new" %>
	          <% end %>
		<% end %>
	</body>
</html>