config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "accounts#index"

  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'accounts/:id/items.csv', to: 'accounts#items_to_csv', as: 'items_to_csv'

  resources :accounts , shallow: true do
      get :multi_exhibit, on: :member
      get :schedule, on: :member
      post :get_comment, on: :member, to: "comments#get_multi_comment"
      get :item_exhibited, to: "items#item_exhibited"
      get :item_not_exhibit, to: "items#item_not_exhibit"
      # get :re_exhibit, to: "items#re_exhibit"
      get :re_exhibit, to: "items#re_exhibit"
      post :re_exhibit, to: "items#exec_re_exhibit",as: 'exec_re_exhibit'

         resources :items, shallow: true do
             get :exhibit, on: :member
             post :get_comment, on: :member, to: "comments#get_comment"
             delete :destroy_multi, on: :collection, to: 'items#destroy_multi'
             resources :comments, shallow: true
             end
         end
end

app/models/account.rb
class Account < ApplicationRecord
    has_many :items, dependent: :destroy
    belongs_to :user
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :account_email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
    validates :account_password, presence: true, length: { in: 1..32 }
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
    before_action :authenticate_user!
    before_action :current_user_check, only: [:show, :edit, :update, :destroy, :multi_exhibit]

    def index
        @accounts = current_user.accounts.all
    end

    def new
        max_account = current_user.max_account - 1
        if max_account >=current_user.accounts.size
          @account = current_user.accounts.new
        else
            redirect_to accounts_path
        end
    end

    def create
        @account = current_user.accounts.new(account_params)
        @account.access_time =  Time.now
        if @account.save
            redirect_to @account
          else
            render :new, status: :unprocessable_entity
          end
    end

    def show
        @account = Account.find(params[:id])
        @items = @account.items.all.reverse_order
    end

    def edit
        @account = Account.find(params[:id])
    end

    def update
        @account = Account.find(params[:id])
        if @account.update(account_params)
            @account.save
            redirect_to @account
        else
          render :edit, status: :unprocessable_entity
        end
    end

    def destroy
      @account = Account.find(params[:id])
      @account.destroy
      redirect_to accounts_path
    end

    def multi_exhibit
        @account = Account.find(params[:id])
        if Time.now - @account.access_time > 120 #現在の時刻と前回の時刻との差が60(新しいリクエストが送られるまで)より大きければtrue
            logger.debug "#{Time.now - @account.access_time}"
            logger.debug '#######pass###########'
            logger.info  'LOGGER TEST >>> info'
            @account.access_time =  Time.now
            @account.save

            @ota = Otamart.new
            driver = @ota.login(@account.account_email,@account.account_password)
            n = 1
            items = @account.random_exhibit ? @account.items.where(url:nil).order("RANDOM()") : @account.items.where(url:nil)#ランダム出品するかどうか
            for item in items.all do #driver.closeしなければならないため、スコープを作らないfor分を使用。
                     file_abs_path = Rails.root.join('public/zip_store', item.csv.to_s + "/exhibit/")
                     @account.access_time =  Time.now#ここで出品中は常に時間を更新することで、2回目に送られてくるリクエストが、Time.now - @account.access_time > 60にtrueにならないようにする
                     @account.save
                     logger.debug '#######after_pass############'
                     logger.debug "#{Time.now - @account.access_time}"
                     logger.debug "#{n}"
                     logger.info  'LOGGER TEST >>> info'
                     url, driver = @ota.multi_exhibit(driver,file_abs_path,item.image1,item.image2,item.image3,item.image4,item.item_name,item.description,item.category1,item.category2,item.category3,
                         item.tags,item.state,item.ship_fee,item.ship_method,item.ship_from,item.ship_day,item.purchase_application,item.discount,item.price)
                     item.url = url
                     item.save

                     unless  @account.min_interval.blank? or @account.max_interval.blank?
                           logger.debug "#{Random.new().rand(@account.min_interval.to_i...@account.max_interval.to_i)}"
                           sleep(Random.new().rand(@account.min_interval.to_i...@account.max_interval.to_i))
                       else
                           sleep(Random.new().rand(5.0..15.0))
                      end

                    n += 1
                    @account.access_time =  Time.now#ここで出品中は常に時間を更新することで、2回目に送られてくるリクエストが、Time.now - @account.access_time > 60にtrueにならないようにする
                    @account.save
            end
            driver.close
            driver.quit
        else
            logger.debug "#{Time.now - @account.access_time}"
            logger.debug '#######no############'
            logger.info  'LOGGER TEST >>> info'
        end
        redirect_to account_path(@account)
    end

    def schedule
        @account = Account.find(params[:id])
    end

    def items_to_csv
      @account = Account.find(params[:id])
      @items = @account.items
    end

    private

    def account_params
        params.require(:account).permit(:account_email, :account_password,:start_time, :min_interval, :max_interval, :random_exhibit)
    end


    def current_user_check
        @account = Account.find(params[:id])
        if @account.user_id != current_user.id
            redirect_to new_user_session_path
        end
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<!-- <form method="post" accept-charset="utf-8" class="form-horizontal col-xs-11" id="change_password_form" action="change-password.html"> -->

<%= form_for @account , html:{ class: "form-horizontal col-xs-11",  id: "change_password_form"} do |f| %>

    <div style="display:none;">
        <!-- <input type="hidden" name="_method" value="POST"/> -->
    </div>

    <!-- <div class="form-group">
        <label class="col-xs-4 control-label">現在のパスワード</label>
        <div class="col-xs-7">
            <input type="password" name="current_password" class="form-control input-sm" id="current-password"/>
        </div>
    </div> -->

    <div class="form-group">
        <label class="col-xs-4 control-label">メールアドレス</label>
        <div class="col-xs-7">
            <%= f.email_field :account_email ,{ class: "form-control input-sm",  id: "password1"} %>
            <!-- <input type="password" name="password1" class="form-control input-sm" id="password1"/> -->
        </div>
    </div>

    <div class="form-group">
        <label class="col-xs-4 control-label">パスワード</label>
        <div class="col-xs-7">
            <%= f.password_field :account_password ,{ class: "form-control input-sm",  id: "password2"} %>
        </div>
    </div>
    <div class="form-group clearfix">
        <button type="submit"  id="change_record" name="change_record" style="margin:0 auto; display:block;" class="btn btn-success ladda-button pull-center">
            <!-- <i class="fa fa-save"></i>  -->
            このオタマートアカウントを登録する
        </button>
    </div>
<!-- </form> -->
<% end %>

app/views/accounts/edit.html.erb
<section class="content-header">
<h1>
    オタマートアカウント編集
</h1>
<ol class="breadcrumb">
    <li>ホーム</li>
    <li class="active"><b>パスワード変更</b></li>
</ol>
</section>

<!-- Main content -->
<section class="content">
<div class="row" id="list_container" name="list_container">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">オタマートアカウント変更</h3>
            </div>

            <div class="box-body table-responsive  with-border" id="main_tbl_wrap" name="main_tbl_wrap">
                <div class="alert alert-warning col-xs-7" style="float: none; margin: 0 auto 20px; display: none;">

                </div>

                <div class="alert alert-info col-xs-7" style="float: none; margin: 0 auto 20px; display: none;">
                    <p style="font-size: 16px;">
                        オタマートアカウントを変更しました。
                    </p>
                </div>


                <%= render 'form' %>

                    <!-- <form method="post" accept-charset="utf-8" class="form-horizontal col-xs-11" id="change_password_form" action="change-password.html"><div style="display:none;"><input type="hidden" name="_method" value="POST"/></div>
                        <div class="form-group">
                        <label class="col-xs-4 control-label">現在のパスワード</label>
                        <div class="col-xs-7">
                            <input type="password" name="current_password" class="form-control input-sm" id="current-password"/>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-xs-4 control-label">新しいパスワード</label>
                        <div class="col-xs-7">
                            <input type="password" name="password1" class="form-control input-sm" id="password1"/>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-xs-4 control-label">新しいパスワード（確認）</label>
                        <div class="col-xs-7">
                            <input type="password" name="password2" class="form-control input-sm" id="password2"/>
                        </div>
                    </div>
                    <div class="form-group clearfix">
                        <button type="submit"  id="change_record" name="change_record" style="margin:0 auto; display:block;" class="btn btn-success ladda-button pull-center"><i class="fa fa-save"></i> セーブ</button>
                    </div>
                   </form> -->

            </div>

            <div id="loading_overlay" class="overlay" style="display: none;">
                <!--                        <img class="fa" src="./images/lib/ajax-loader1.gif">-->
                <!-- <i class="fa fa-refresh fa-spin"></i> -->
            </div>
        </div>
    </div>
</div>
</section>

app/views/accounts/index.html.erb
<section class="content-header">
    <h1>
        アカウント管理
    </h1>
    <ol class="breadcrumb">
        <li>
            ホーム
        </li>
        <li class="active">
            <b>アカウント管理</b>
        </li>
    </ol>
</section>

<section class="content">
    <div class="row" id="list_container">
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">アカウント一覧</h3>
                </div>

                <div class="box-body" id="main_tbl_wrap">
                    <div class="col-lg-2" style="padding: 0;">
                        <div class="panel panel-primary">
                            <div class="panel-heading text-center">契約状態</div>
                            <div class="panel-body" style="min-height: 150px">
                                <% if current_user.max_account > current_user.accounts.size%>
                                     <p><%= link_to 'オタマートアカウント登録', new_account_path %></p>
                                 <% else %>
                                     <p>アカウント数の上限に達しています。作成できません</p>
                                <% end %>
                                基本契約:<%= current_user.max_account  %><br>
                                残り枠:<%= current_user.max_account - current_user.accounts.size %><br>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-10">
                        <div id="mainTbl_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="dataTables_length" id="mainTbl_length">
                                    </div>
                                    <div class="col-sm-6">
                                        <div id="mainTbl_filter" class="dataTables_filter">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12">

                                    <table id="mainTbl" class="table table-hover table-responsive  with-border dataTable no-footer" role="grid" aria-describedby="mainTbl_info" border="1">
                                        <thead>
                                            <tr role="row">
                                                <th class="sorting_disabled" rowspan="1" colspan="1" style="width: 40px;">No</th>
                                                <th class="sorting_disabled" rowspan="1" colspan="1" style="width: 192px;">オタマートアカウントID</th>
                                                <th class="sorting_disabled" rowspan="1" colspan="1" style="width: 104px;">メールアドレス</th>
                                                <th class="sorting_disabled" rowspan="1" colspan="1" style="width: 104px;">パスワード</th>
                                                <th class="sorting_disabled" rowspan="1" colspan="1" style="width: 49px;">操作</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <% @accounts.each do |account| %>
                                                    <tr role="row" class="odd">
                                                        <td><%= account.id %></td>
                                                        <td></td>
                                                        <td><%= account.account_email %></td>
                                                        <td><%= account.account_password %></td>
                                                        <td>
                                                            <%= link_to '詳細', account , class: "btn btn-primary btn-sm" , style: "display:block;margin-bottom:5px;"  %>
                                                            <%= link_to '編集', edit_account_path(account) , class: "btn btn-danger btn-sm", style: "display:block;margin-bottom:5px;" %>
                                                            <%= link_to '削除', account_path(account),method: :delete, data: { confirm: '削除しますか？' } , class: "btn btn-warning btn-sm", style: "display:block;margin-bottom:5px;" %>
                                                        </td>
                                                    </tr>
                                            <% end %>
                                        </tbody>

                                    </table>
                    </div>
                </div>

                <div id="loading_overlay" class="overlay" style="display: none;">
                    <i class="fa fa-refresh fa-spin"></i>
                </div>

            </div>
        </div>
    </div>
</section>

app/views/accounts/new.html.erb
<section class="content-header">
<h1>
    オタマートアカウント登録
</h1>
<ol class="breadcrumb">
    <li>ホーム</li>
    <li class="active"><b>パスワード変更</b></li>
</ol>
</section>

<!-- Main content -->
<section class="content">
<div class="row" id="list_container" name="list_container">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">オタマートアカウント登録</h3>
            </div>

            <div class="box-body table-responsive  with-border" id="main_tbl_wrap" name="main_tbl_wrap">
                <div class="alert alert-warning col-xs-7" style="float: none; margin: 0 auto 20px; display: none;">

                </div>

                <div class="alert alert-info col-xs-7" style="float: none; margin: 0 auto 20px; display: none;">
                    <p style="font-size: 16px;">
                        オタマートアカウントを登録しました。
                    </p>
                </div>


                <%= render 'form' %>

                    <!-- <form method="post" accept-charset="utf-8" class="form-horizontal col-xs-11" id="change_password_form" action="change-password.html"><div style="display:none;"><input type="hidden" name="_method" value="POST"/></div>
                        <div class="form-group">
                        <label class="col-xs-4 control-label">現在のパスワード</label>
                        <div class="col-xs-7">
                            <input type="password" name="current_password" class="form-control input-sm" id="current-password"/>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-xs-4 control-label">新しいパスワード</label>
                        <div class="col-xs-7">
                            <input type="password" name="password1" class="form-control input-sm" id="password1"/>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-xs-4 control-label">新しいパスワード（確認）</label>
                        <div class="col-xs-7">
                            <input type="password" name="password2" class="form-control input-sm" id="password2"/>
                        </div>
                    </div>
                    <div class="form-group clearfix">
                        <button type="submit"  id="change_record" name="change_record" style="margin:0 auto; display:block;" class="btn btn-success ladda-button pull-center"><i class="fa fa-save"></i> セーブ</button>
                    </div>
                   </form> -->

            </div>

            <div id="loading_overlay" class="overlay" style="display: none;">
                <!--                        <img class="fa" src="./images/lib/ajax-loader1.gif">-->
                <!-- <i class="fa fa-refresh fa-spin"></i> -->
            </div>
        </div>
    </div>
</div>
</section>

app/views/accounts/schedule.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        スケジュール
<!--            <small>User Management</small>-->
    </h1>
    <ol class="breadcrumb">
        <li>
            <!-- <i class="fa fa-home"></i> -->
            ホーム
        </li>
        <li class="active">
            <!-- <i class="fa fa-calendar"></i>  -->
            <b>スケジュール</b>
        </li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row" id="list_container" name="list_container">
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <!-- <i class="fa fa-calendar"></i> -->
                    <h3 class="box-title">スケジュール</h3>
                </div>
                <div class="alert alert-info col-xs-7" style="float: none; margin: 0 auto 20px; display: none;">
                    <p style="font-size: 16px;">
                        保存しました。
                    </p>
                </div>

                <div class="alert alert-warning col-xs-7" style="float: none; margin: 0 auto 20px; display: none;">
                    <!-- <h3 style="margin-top: 0px; ">ごめんなさい!</h3>-->
                </div>

                <% if @account.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= @account.errors.count %>件のエラーが発生したため保存ができませんでした。</h2>
                      <ul>
                      <% @account.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                      <% end %>
                      </ul>
                    </div>
                <% end %>


                <%= form_for @account , html: {class: 'form-horizontal col-xs-7' , id: "user_setting_form" , style: "float:none; margin: 0 auto"} do |f| %>
                    <div style="display:none;"><input type="hidden" name="_method" value="PUT"/></div>
                    <input type="hidden" name="product_current_count" id = "product_current_count" value="">
                    <div class="form-group">
                        <br>
                    </div>

                    <div class="form-group">
                        <label class="col-xs-3 control-label">出品開始時刻 : <br/><span style="font-size: 10px; color:gray;">(24時間表記:0~23）</span></label>
                        <div class="col-xs-8">
                            <!-- <input type="text" name="start_hour" class="form-control input-sm" maxlength="2" oninput="checktime(this);" id="start-hour" value="0"/> -->
                             <%= f.select(:start_time, [  [1, 1], [2, 2], [3, 3], [4, 4],[5, 5], [6, 6],[7, 7], [8, 8],[9, 9], [10, 10],[11, 11], [12, 12], [13, 13], [14, 14],[15, 15], [16, 16],[17, 17], [18, 18],[19, 19], [20, 20], [21, 21], [22, 22], [23, 23], [24, 24]] ,  { class: "form-control input-sm", id: "start-hour" }) %>
                        </div>
                    </div>

                    <!-- <div class="form-group">
                        <label class="col-xs-3 control-label">再出品間隔 : <br/><span style="font-size: 10px; color:gray;">(単位:時)</span></label>
                        <div class="col-xs-8"><input type="text" name="publish_interval" class="form-control input-sm" maxlength="2" oninput="checkNumber(this);" required="required" id="publish-interval" value="2"/></div>
                     </div>

                    <div class="form-group">
                        <label class="col-xs-3 control-label">一日の最大出品回数 :</label>
                        <div class="col-xs-8"><input type="text" name="repeat_count" class="form-control input-sm" maxlength="2" oninput="checkNumber(this);" id="repeat-count" value="10"/></div>
                     </div> -->

                    <div class="form-group">
                        <label class="col-xs-3 control-label">最低間隔 : <br/><span style="font-size: 10px; color:gray;">(単位:分)</span></label>
                        <div class="col-xs-8">
                            <!-- <input type="text" name="republish_interval_min" class="form-control input-sm" maxlength="2" oninput="checkNumber(this);" required="required" id="republish-interval-min" value="15"/> -->
                            <%= f.text_field :min_interval ,  { class: "form-control input-sm", id: "republish-interval-min" } %><br>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-xs-3 control-label">最大間隔 : <br/><span style="font-size: 10px; color:gray;">(単位:分)</span></label>
                        <div class="col-xs-8">
                            <!-- <input type="text" name="republish_interval_max" class="form-control input-sm" maxlength="2" oninput="checkNumber(this);" required="required" id="republish-interval-max" value="20"/> -->
                            <%= f.text_field :max_interval ,  { class: "form-control input-sm", id: "republish-interval-max" } %><br>
                        </div>
                    </div>

                    <!-- <div class="form-group">
                        <label class="col-xs-3 control-label">今月の目標  : <br/><span style="font-size: 10px; color:gray;">(単位:円)</span></label>
                        <div class="col-xs-8"><input type="text" name="target_of_month" class="form-control input-sm" maxlength="11" oninput="checkNumber(this);" required="required" id="target-of-month" value="0"/></div>
                    </div> -->

                    <div class="form-group">
                        <label class="col-xs-3 control-label">ランダム出品 : <br/></label>
                        <div class="col-xs-8">
                            <!-- <input id="switch_random_order" name="switch_random_order" type="checkbox" data-label-text="ランダム出品有効" > -->
                            <%= f.select(:random_exhibit, [["しない", 0], ["する", 1]] ,  { class: "form-control input-sm", id: "switch_random_order" , type:"checkbox"}) %><br>
                        </div>
                    </div>

                <div class="form-group">
                        <button type="submit" class="btn btn-success" style="float:none;display:block;margin:0 auto;">
                            <!-- <i class="fa fa-save (alias)"></i> -->
                             保存
                        </button>
                        <%# <%= f.submit "保存" %>
                    </div>
                <% end %>



                <div id="loading_overlay" class="overlay" style="display: none;">
<!--                        <img class="fa" src="./images/lib/ajax-loader1.gif">-->
                    <i class="fa fa-refresh fa-spin"></i>
                </div>

                <div class="box-footer">
                    <div class="box-header with-border">

                    </div>
                </div>

            </div>
        </div>
    </div>
</section>



<%# <%= form_for @account do |f| %>
<%# if @account.errors.any? %>
    <!-- <div id="error_explanation">
      <h2><%= @account.errors.count %>件のエラーが発生したため保存ができませんでした。</h2>
      <ul> -->
      <%# @account.errors.full_messages.each do |msg| %>
        <!-- <li><%#= msg %></li> -->
      <%# end %>
      <!-- </ul>
    </div> -->
<%# end %>
          <%#=# f.label :start_time, "開始時刻 " %>
          <%#=# f.select(:start_time, [  [1, 1], [2, 2], [3, 3], [4, 4],[5, 5], [6, 6],[7, 7], [8, 8],[9, 9], [10, 10],[11, 11], [12, 12], [13, 13], [14, 14],[15, 15], [16, 16],[17, 17], [18, 18],[19, 19], [20, 20], [21, 21], [22, 22], [23, 23], [24, 24]]) %><br>

          <%#= f.label :min_interval, "最低間隔（単位：分）" %>
          <%#= f.text_field :min_interval %><br>

          <%#= f.label :max_interval,   "最高間隔（単位：分）" %>
          <%#= f.text_field :max_interval %><br>

          <%#= f.label :random_exhibit, "ランダム出品 " %>
          <%#= f.select(:random_exhibit, [["しない", 0], ["する", 1]]) %><br>

          <%#=# f.submit "保存" %>

<%#end %>

app/views/accounts/show.html.erb
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
            </div>
            <div class="col-lg-4 text-center">
                <h1><商品一括登録></h1>
                <h3>商品データのアップロード</h3>
                <div>
                    <%= render "items/form" %>
                </div>

                <div>
                    <strong>開始時刻:</strong>
                    <%= @account.start_time %>|
                    <strong>最低間隔:</strong>
                    <%= @account.min_interval %>|
                    <strong>最高間隔:</strong>
                    <%= @account.max_interval %>|
                    <strong>ランダム出品:</strong>
                    <%= @account.random_exhibit %>
                </div>

                <div class="text-center">
                    <%= link_to '商品エクスポート(csv取得)',items_to_csv_path(@account),{format: :csv, :id =>"download_all_products" ,:class => "btn btn-warning"} %>
                </div>
            </div>
            <div class="col-lg-4">
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-lg-2"></div>
            <div class="col-lg-8 text-center">
                <% if @items.size > 0 %>
                        <p>
                            <%= link_to 'すべて出品', multi_exhibit_account_path(@account),class: :"btn btn-outline-success" %>
                            <%= link_to 'すべてのコメント取得', get_comment_account_path(@account), method: :post , class: :"btn btn-outline-success" %>
                        </p>
                <% else %>
                        <div class="alert alert-dismissible alert-warning ">
                          <button type="button" class="close" data-dismiss="alert">&times;</button>
                          <h4 class="alert-heading">商品が登録されていません</h4>
                        </div>
                <% end %>
            </div>
            <div class="col-lg-2"></div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <% @items.each do |item| %>
                <div class="col-lg-4">
                    <table class="table">
                      <thead>
                        <tr class="table-active">
                          <th scope="col">商品名</th>
                          <th scope="col"><%= item.item_name %></th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr class="table-light">
                          <th scope="row">ステータス</th>
                          <td>
                              <% unless item.url.blank? %>
                                出品済み
                                <% else %>
                                未出品=><%= link_to '出品する', exhibit_item_path(item) %>
                              <% end %>
                          </td>
                        </tr>
                        <tr class="table-light">
                          <th scope="row">画像</th>
                          <td>
                              <%= image_tag("/zip_store/" + item.csv.to_s + "/exhibit/"  + item.image1, :id => "photo_1_preview", :size => "150x150") %>
                          </td>
                        </tr>
                        <tr class="table-light">
                          <th scope="row">未返信コメント</th>
                          <td>
                              <% if item.new_comment %>
                                     あり
                              <% else %>
                                     なし
                              <% end %>
                              (id:<%= item.id %>)
                          </td>
                        </tr>
                        <tr class="table-light">
                          <th scope="row"></th>
                          <td>
                              <% unless item.id.blank? %>
                                   <p>
                                       <%= link_to '商品詳細', item_path(item),  account_id:item.account_id ,class: :"btn btn-outline-success" %>
                                       <%= link_to '削除', item_path(item),  method: :delete, data: { confirm: '削除しますか？' } ,class: :"btn btn-outline-success"%>
                                   </p>
                              <% end %>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                </div>
            <% end %>
        </div>
    </div>